name: Deploy storybook on gh-pages
on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build storybook
        run: npm run build-storybook
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
